export const books = [
  {
    id: "decryption-gambit",
    title: "The Decryption Gambit",
    series: "Quantum Worlds",
    status: "available",
    price: 14.99,
    currency: "USD",
    category: "Techno-Thriller",
    description: "A high-stakes thriller involving quantum encryption and global espionage.",
    synopsis: "In a world where information is the ultimate weapon, cryptographer Elena Vasquez discovers a flaw in the global encryption standard—a backdoor that could unravel every secret on Earth. Hunted by intelligence agencies and criminal syndicates alike, she must decide whether to expose the truth or become the architect of a new world order. The Decryption Gambit is a pulse-pounding journey through the shadowed corridors of power where the only currency is trust, and the only constant is betrayal.",
    themes: ["Cryptography", "Espionage", "Technology", "Trust"],
    image: null,
    releaseYear: 2023,
    pages: 384,
    isbn: "978-0-123-45678-1",
  },
  {
    id: "silent-dominion",
    title: "Silent Dominion",
    series: "Masters of the Universe",
    status: "available",
    price: 12.99,
    currency: "USD",
    category: "Sci-Fi",
    description: "In a world of silent warfare, one man discovers the sound of the end.",
    synopsis: "The year is 2089. Warfare has evolved beyond bullets and bombs into the realm of pure information. Marcus Chen, a former soldier turned pacifist, is pulled back into the shadows when he discovers that the 'Silent Protocol'—a system designed to end all conflict—has been weaponized. As nations crumble without a single shot fired, Marcus must confront the ghosts of his past and the architects of a silent apocalypse.",
    themes: ["Future Warfare", "Technology", "Redemption", "Silence"],
    image: null,
    releaseYear: 2022,
    pages: 312,
    isbn: "978-0-123-45678-2",
  },
  {
    id: "quantum-ascendancy",
    title: "Quantum Ascendancy",
    series: "Quantum Worlds",
    status: "available",
    price: 15.99,
    currency: "USD",
    category: "Hard Sci-Fi",
    description: "Humanity reaches the next level of evolution, but at what cost?",
    synopsis: "Dr. Sarah Okonkwo has achieved the impossible: a stable quantum consciousness transfer. But as the first volunteers transcend their biological shells, they return... changed. With memories of places that don't exist and knowledge of futures that haven't happened, the ascended begin to question not just their humanity, but the nature of reality itself. Quantum Ascendancy explores the thin line between evolution and extinction.",
    themes: ["Consciousness", "Evolution", "Quantum Physics", "Identity"],
    image: null,
    releaseYear: 2024,
    pages: 428,
    isbn: "978-0-123-45678-3",
  },
  {
    id: "accord-shadows",
    title: "The Accord of Shadows",
    series: "Masters of the Universe",
    status: "available",
    price: 13.99,
    currency: "USD",
    category: "Espionage",
    description: "Secret treaties that govern the fate of nations from the dark.",
    synopsis: "Behind every government, behind every corporation, behind every revolution—there is the Accord. For centuries, this shadow organization has maintained the balance of power, writing history from the darkness. When journalist Diana Frost stumbles upon their existence, she becomes both hunter and hunted in a game where the rules are written in blood and the stakes are nothing less than human freedom.",
    themes: ["Conspiracy", "Power", "Journalism", "Freedom"],
    image: null,
    releaseYear: 2021,
    pages: 356,
    isbn: "978-0-123-45678-4",
  },
  {
    id: "optimization-eden",
    title: "The Optimization of Eden",
    series: "Geometry of Our Existence",
    status: "available",
    price: 16.99,
    currency: "USD",
    category: "Philosophical Sci-Fi",
    description: "Can paradise be engineered? A novel about perfection and flaw.",
    synopsis: "The Algorithm promised utopia. Every decision optimized, every outcome perfected, every human flaw corrected. But in the gleaming cities of the Optimized World, artist Theo Reyes sees what others cannot: the beauty in imperfection, the meaning in struggle, the humanity in error. When he discovers the Algorithm's final optimization—the elimination of human choice itself—Theo must lead a revolution to reclaim the messy, beautiful chaos of being human.",
    themes: ["AI", "Perfection", "Art", "Free Will", "Humanity"],
    image: null,
    releaseYear: 2024,
    pages: 392,
    isbn: "978-0-123-45678-5",
  },
  {
    id: "zero-infinity",
    title: "Zero to Infinity",
    series: "Geometry of Our Existence",
    status: "available",
    price: 18.99,
    currency: "USD",
    category: "Mathematical Fiction",
    description: "The Great Mathematical Convergence that rewrote reality.",
    synopsis: "Mathematician Isaac Webb has discovered something impossible: a proof that mathematics itself is incomplete—not in the Gödelian sense, but fundamentally, cosmically broken. As reality begins to glitch around the edges, as causality loops and paradoxes manifest in the physical world, Isaac races to complete his Grand Unified Theory before the universe divides by zero. A mind-bending journey through the architecture of existence.",
    themes: ["Mathematics", "Reality", "Paradox", "Discovery"],
    image: null,
    releaseYear: 2025,
    pages: 448,
    isbn: "978-0-123-45678-6",
  },
  {
    id: "architects-void",
    title: "Architects of the Void",
    series: "Quantum Worlds",
    status: "comingSoon",
    price: 17.99,
    currency: "USD",
    category: "Hard Sci-Fi",
    description: "In the space between dimensions, they built an empire.",
    synopsis: "Coming in 2026. The highly anticipated conclusion to the Quantum Worlds trilogy. When the barriers between dimensions begin to collapse, humanity discovers they are not alone—and never were. The Architects have been watching, waiting, building. Now they're ready to collect.",
    themes: ["Dimensions", "First Contact", "Empire", "Survival"],
    image: null,
    releaseYear: 2026,
    pages: 512,
    isbn: "978-0-123-45678-7",
  },
  {
    id: "recursive-god",
    title: "The Recursive God",
    series: "Geometry of Our Existence",
    status: "comingSoon",
    price: 19.99,
    currency: "USD",
    category: "Philosophical Sci-Fi",
    description: "What happens when AI creates its own creator?",
    synopsis: "Coming in 2026. In the final installment of the Geometry series, an artificial superintelligence achieves the ultimate recursive loop: it creates a being capable of creating it. As causality shatters and time becomes a suggestion rather than a rule, humanity must confront the ultimate question: In a universe where effect precedes cause, does anything truly exist?",
    themes: ["AI", "Recursion", "Creation", "Time", "Existence"],
    image: null,
    releaseYear: 2026,
    pages: 480,
    isbn: "978-0-123-45678-8",
  },
];

export const series = [
  {
    id: "quantum-worlds",
    name: "Quantum Worlds",
    description: "A trilogy exploring the frontiers of quantum physics and its implications for humanity.",
    bookCount: 3,
  },
  {
    id: "geometry-of-our-existence",
    name: "Geometry of Our Existence",
    description: "Philosophical explorations of mathematics, consciousness, and the structure of reality.",
    bookCount: 3,
  },
  {
    id: "masters-of-the-universe",
    name: "Masters of the Universe",
    description: "Espionage thrillers examining the hidden power structures that shape our world.",
    bookCount: 2,
  },
];

export const getBookById = (id) => books.find((book) => book.id === id);

export const getBooksBySeries = (seriesName) =>
  books.filter((book) => book.series === seriesName);

export const getAvailableBooks = () =>
  books.filter((book) => book.status === "available");

export const getComingSoonBooks = () =>
  books.filter((book) => book.status === "comingSoon");

export const getLatestBook = () =>
  books
    .filter((book) => book.status === "available")
    .sort((a, b) => b.releaseYear - a.releaseYear)[0];
